[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "ling-arg=dynamic_lookup"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "ling-arg=dynamic_lookup"]
